## Absolute path of the tools ##
tools:
  bcftools : bcftools
  rtg : rtg
  truvari : truvari
  bgzip : bgzip
  tabix : tabix
  cdhit_est : cd-hit
  Rscript : Rscript


databases:
  dbSNP : databases/DBSNP_SNP.txt
  gnomAD : databases/GNOMAD_SNP.txt
  Genomes_1000 : databases/1000Genome_SNP.txt
  GME : databases/GME_SNP.txt
  GNOMAD_INDEL : databases/GNOMAD_INDEL.txt
  Genomes_1000_INDEL : databases/1000Genome_INDEL.txt
  GME_INDEL : databases/GME_INDEL.txt
  DGV_SV_INS : databases/DGV_SV_INS.txt
  Genomes_1000_SV_DEL : databases/1000Genome_SV_DEL.txt
  DGV_SV_DEL : databases/DGV_SV_DEL.txt

classes:
  reciprocal_overlap : reciprocal_overlap
