## Absolute path of the tools ##
tools:
  bcftools : /usr/local/bin/bcftools
  rtg : /mnt/h700/omixlab/packages/bipin_packages/miniconda3/bin/rtg

databases:
  dbSNP : databases/DBSNP_SNP.txt
  gnomAD : databases/GNOMAD_SNP.txt
  Genomes_1000 : databases/1000Genome_SNP.txt
  GME : databases/GME_SNP.txt
  GNOMAD_INDEL : databases/GNOMAD_INDEL.txt
  Genomes_1000_INDEL : databases/1000Genome_INDEL.txt
  GME_INDEL : databases/GME_INDEL.txt
  DGV_SV_INS : databases/DGV_SV_INS.txt
  Genomes_1000_SV_DEL : databases/1000Genome_SV_DEL.txt
  DGV_SV_DEL : databases/DGV_SV_DEL.txt

classes:
  reciprocal_overlap : reciprocal_overlap
